### ISSUE TITLE
error: file to import not found or unreadable: '.meteor/local/build/programs/server/assets/packages/meteoric_ionicons-sass/ionicons'

### ISSUE THREAD

**Issue by kldeb** [meteoric/ionicons-sass#1]
I'm getting the following error when starting meteor after adding this package via meteor add:

```
error: file
   to import not found or unreadable:
   '.meteor/local/build/programs/server/assets/packages/meteoric_ionicons-sass/ionicons'
```

The file is missing and there is no other error. 

I noticed that I have 2 versions of the package in /Users/me/.meteor/packages/meteoric_ionicons-sass 
- 0.1.2
- 0.1.5

Any idea what's causing this?

**Comment by nickw** [comment]
I think you are just getting the Meteor/SASS error described here: https://github.com/meteoric/ionic-sass#installation. It should work when you restart your server.

**Comment by kldeb** [comment]
I tried restarting multiple times. The error persists.

**Comment by vertangelx** [comment]
@nickw @aireater Getting the same error. Restarting doesnt help. I do not see the folder `.meteor/local/build/programs/server/assets/packages/meteoric_ionicons-sass`

**Comment by kldeb** [comment]
@vertangelx I didn't have time to figure it out. I went with ratchet instead.

**Comment by jupiterkenji** [comment]
I have this problem too and restarting not helping

**Comment by certor** [comment]
I had the same issue with this import, the folder for the build under local/.../meteoric_ionicons-sass was not being created at all, I noticed I had version 0.1.2, so I went ahead and try to add the meteoric_ionicons-sass@0.1.5, but it also failed to create the folder, then I removed the package and let meteor to add the default one, so this time it ended up installing 0.1.6, which seems to solve this issue ... now the folder is created and the server initializes without errors ...
