### ISSUE TITLE
swipe left on list item to show edit/delete

### ISSUE THREAD

**Issue by markshust** [meteoric/ionicons-sass#11]
How does one do this with meteoric? This is the functionality I'm referencing -- swipe left to delete/edit a list item http://ionicframework.com/docs/api/directive/ionList/

**Comment by nickw** [comment]
This is not currently possible "out of the box", but there has been some progress on adding it: https://github.com/meteoric/meteor-ionic/issues/7

**Comment by markshust** [comment]
Thanks, will try to implement and submit a PR to get this going again.
