### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by digilord** [meteoric/ionicons-sass#3]
The ionicons are missing in the 0.1.2 version in atmosphere. The directory that is supposed to contain the assets does not exist. I have removed the package and re-added it. This does not resolve the issue. After restarting it does not exist.

**Comment by vertangelx** [comment]
Same problem here

**Comment by nickw** [comment]
Can you upgrade to `0.1.6`?

**Comment by richpowell** [comment]
use 0.1.6, and dont forget to at the import statement like the docs say. I missed that step only to have a empty button box...

**Comment by svda** [comment]
0.1.17 here and same problem.

**Comment by DenLilleMand** [comment]
Same problem here. 
meteoric:autoform-ionic    0.1.5  Ionic theme for Autoform
meteoric:ionic             0.1.17  Ionic components for Meteor. No Angular!
meteoric:ionic-sass        0.1.9  Ionic's CSS Framework in SASS and bundled for Meteor.
meteoric:ionicons-sass     0.1.6  Ionic's Ionicons library in SASS and bundled for Meteor.

**Comment by augustochaves** [comment]
Same here:
meteoric:autoform-ionic@0.1.5
meteoric:ionic@0.1.17
meteoric:ionic-sass@0.1.9
meteoric:ionicons-sass@0.1.6
