### ISSUE TITLE
Import path 

### ISSUE THREAD

**Issue by wolasss** [meteoric/ionicons-sass#4]
Hi,

The way it is supposed to import sass files: (`@import '.meteor/local/build/programs/server/assets/packages/meteoric_ionicons-sass/ionicons';`) it's not really good idea. 

Firstly, when you have package-oriented meteor structure, so that every logical unit is in seperate package, then, when you put this import inside a package, this path is simply wrong. 

What's more, this path also will be wrong when you bundle the app and run it as a bundled node meteor application. 

So it would be nice if we could figure out best way of importing it.

**Comment by nickw** [comment]
You don't _have_ to use this `@import` syntax, I just use it so that I can override the SASS variables. If the paths are causing issues in your app you can just copy the files into your codebase. SASS `@import`s in Meteor are definitely buggy, but that is a Meteor-core issue.

**Comment by sasikanth513** [comment]
@nickw without `@import` styles are not loading, Is this normal or Is this some kind of bug/issue with my app?

If I use `@import` everything is fine

**Comment by nickw** [comment]
@sasikanth513 I'm not sure I follow, but to use the Ionic styles you either need to:

1- use this package and `@import` the SCSS files
2- use another meteor package
3- grab the static CSS files from ionicframework.com and drop them in your Meteor app

**Comment by sasikanth513** [comment]
@nickw Thanks for the quick reply.

One more doubt, For example I don't want `_forms.scss` file(it is overriding my existing styles)

Is there any way to avoid particulat files or particular styles  otherthan cloning the repo?

**Comment by nickw** [comment]
You can probably just duplicate [this file](https://github.com/meteoric/ionic-sass/blob/master/_ionic.scss) in your own app and only import the files you want.
