### ISSUE TITLE
Can’t Update meteoric:ionicons-sass Package

### ISSUE THREAD

**Issue by adrianalexeio** [meteoric/ionicons-sass#6]
Meteor 1.1.0.2 informs me that new versions of packages installed are available to update.

```
meteoric:ionic-sass 0.1.3* Ionic's CSS Framework in SASS and bundled for ...
meteoric:ionicons-sass 0.1.2* Ionic's Ionicons library in SASS and bundled f...

* New versions of these packages are available! Run 'meteor update' to try to
update those packages to their latest versions. If your packages cannot be
updated further, try typing meteor add <package>@<newVersion> to see more
information.
```

I try meteor update or meteor add, but this doesn't make those packages get updated.

**Comment by lirbank** [comment]
Heya @adrianalexeio, see my comment in #5 - could be the same issue.

**Comment by adrianalexeio** [comment]
Thank you @lirbank. It works after i uninstall all meteoric related packages and reinstall with following order:

```
meteoric:ionicons-sass
meteoric:ionic-sass
meteoric:ionic
```

now i got fourseven 2.0.1_5 instead 3.0.0

**Comment by lirbank** [comment]
Great! I think you could also just remove the `versions` file all together and let Meteor rebuild it. Anyhow, glad it worked!
